apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookshelf
  namespace: bookshelf
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: bookshelf
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
