apiVersion: v1
kind: Service
metadata:
  name: bookshelf
  namespace: bookshelf
spec:
  type: NodePort
  selector:
    app: bookshelf
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
